// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package evercorepostgres

import (
	"database/sql"
	"time"
)

type Aggregate struct {
	ID              int64
	AggregateTypeID int64
	NaturalKey      sql.NullString
}

type AggregateType struct {
	ID   int64
	Name string
}

type Event struct {
	ID          int64
	AggregateID int64
	Sequence    int64
	EventTypeID int64
	State       string
	EventTime   time.Time
	Reference   string
}

type EventType struct {
	ID   int64
	Name string
}

type Snapshot struct {
	ID          int64
	AggregateID int64
	Sequence    int64
	State       string
}
